### ISSUE TITLE
predict_eval.py

### ISSUE THREAD

**Issue by wangqinghahaha** [csccsccsccsc/cpp-net#5]
Traceback (most recent call last):
  File "D:\WQ\cpp-net-main1\cppnet\predict_eval.py", line 230, in <module>
    run(
  File "D:\WQ\cpp-net-main1\cppnet\predict_eval.py", line 173, in run
    star_label = predict_each_image(
  File "D:\WQ\cpp-net-main1\cppnet\predict_eval.py", line 66, in predict_each_image
    coord = dist_to_coord(dist_numpy)
TypeError: dist_to_coord() missing 1 required positional argument: 'points'

i cant run this file correctly

**Comment by csccsccsccsc** [comment]
try installing stardist==0.6.0
